### ISSUE TITLE
add the ladies back

### ISSUE THREAD

**Issue by Helianthella** [themanaworld/tmwa-client-data#338]
turn some npcs into female, for more diversity (right now they all have male sprite)
we could turn some male npcs into female too

**Comment by wushin** [comment]
[] Eomie
[] Elanore
[] Sarah
[] Gwendolyn
[] Estrilda
[] Inar
[] Swezanne
[] Cyndale
[] Silva
[] Hetchel
[] Latoy
[] Candide
[] Rebecca
[] Sara
[] Old Woman
[] Sabine
[] Airila

**Comment by nashley** [comment]
Why did all the NPCs become male?

**Comment by wushin** [comment]
Because we were going to make only N available and no one flipped the NPCs to use the M & F faces.

**Comment by wushin** [comment]
Here is the list of NPC Id's that should be female.

- [ ] 106
- [ ] 108
- [ ] 118
- [ ] 119
- [ ] 140
- [ ] 144
- [ ] 151
- [ ] 154
- [ ] 163
- [ ] 164
- [ ] 165
- [ ] 167
- [ ] 175
- [ ] 177
- [ ] 182
- [ ] 190
- [ ] 195
- [ ] 196
- [ ] 201
- [ ] 205
- [ ] 206
- [ ] 207
- [ ] 208
- [ ] 209
- [ ] 210
- [ ] 301
- [ ] 340
- [ ] 355
- [ ] 356
- [ ] 360
- [ ] 361
- [ ] 363
- [ ] 370
- [ ] 371
- [ ] 376
- [ ] 377
- [ ] 393
- [ ] 401
- [ ] 404
- [ ] 406
